# Site settings
title: Marad Blog
email: moriturius@gmail.com
timezone: Europe/Warsaw
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.radoszewski.pl" # the base hostname & protocol for your site
twitter_username: moriturius
github_username:  marad

# Build settings
markdown: kramdown

permalink: date

defaults:
  -
    scope:
      path: ""
      type: "drafts"
    values:
      author: "marad"
      layout: "post"
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "marad"
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      author: "marad"
      layout: "page"
